name: Compile Sketch
on:
  - push
  - pull_request

jobs:
  build-for-esp8266:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - esp8266:esp8266:nodemcuv2

    steps:
      - uses: actions/checkout@v3
      - name: Prepare Arduino IDE compatibility
        run: |
          cp include/wifi_secrets.h.example include/wifi_secrets.h
          cd scripts
          sh migrate_to_ino.sh
      - uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - ./esp8266-wifi-participant
          cli-compile-flags: |
            - --warnings="none"
