name: ðŸ”¨ Compile Sketch
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  compile-sketch:
    name: ${{ matrix.fqbn }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - esp8266:esp8266:nodemcuv2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Prepare Arduino IDE compatibility
        run: |
          cd scripts
          sh migrate_to_ino.sh

      - name: Compile sketch
        uses: arduino/compile-sketches@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: |
            - ./esp8266-ota-capable
          cli-compile-flags: |
            - --preprocess
