name: Compile Sketch
on:
  push:
  pull_request:

jobs:
  build-for-esp8266:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        fqbn:
          - esp8266:esp8266:nodemcuv2

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Prepare Arduino IDE compatibility
        run: |
          cd scripts
          sh migrate_to_ino.sh
      - uses: arduino/compile-sketches@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          libraries:  |
            - source-url: https://github.com/marvinroger/async-mqtt-client/archive/master.zip
            - source-url: https://github.com/me-no-dev/ESPAsyncTCP/archive/master.zip
          sketch-paths: |
            - ./esp8266-mqtt-client
          cli-compile-flags: |
            - --preprocess
