name: CPP Lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  cpp-lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: CPP Lint
        uses: cpp-linter/cpp-linter-action@v2.13.3
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          thread-comments: true
          extra-args: -Iinclude/

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        shell: bash
        run: |
          #!/bin/bash
          echo "Some files failed the linting checks!"
          # for actual deployment
          # exit 1
