name: CPP Lint Full

on:
  push:
    branches:
      - main
      - merge-upstream
      - renovate/cpp-linter-**
  workflow_dispatch:

permissions:
  issues: write

jobs:
  cpp-lint-full:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: cpp-linter/cpp-linter-action@v2.11.0
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file
        files-changed-only: false
        #thread-comments: true - currently not working
        extra-args: -Iinclude/

    - name: Fail fast?!
      if: steps.linter.outputs.checks-failed > 0
      run: echo "Some files failed the linting checks!"
      # for actual deployment
      # run: exit 1
